name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KIM }}
      -name : ADD SSH KEY maeng17
        run : |
          echo "${{secrets.DEPLOY_MAENG17}}" > ~/.ssh/maeng17
          chmod 600 ~/.ssh/maeng17
          ssh-add ~/.ssh/maeng17

      - name: Deploy to EC2
        run: |
          ssh ec2-user@43.203.233.134 "cd /home/ec2-user/JAFAR && git pull && ./deploy.sh"
